### ISSUE TITLE
Incidental error on lobby creation

### ISSUE THREAD

**Issue by pavelruzicka** [ChrisRu/ludo-api#1]
**Summary:**

API throws an unexpected error on lobby creation

**Steps to reproduce:**

Invoke `lobby:create` with a non-existent lobby name

**Expected results:**

Lobby gets created without an error being thrown

**Actual results:**

Lobby gets created, an error gets thrown simultaneously

**Relevant output:**

`Error: An unexpected error occurred invoking 'lobby:create' on the server.`

**Comment by ChrisRu** [comment]
Fixed in 41b4a93e3c550a5d5a466ccc87f4589792fe8ae7
