### ISSUE TITLE
Error message formatting mishap

### ISSUE THREAD

**Issue by pavelruzicka** [ChrisRu/ludo-api#2]
**Summary:**

Lobby name in error message is prefixed with a dollar sign

**Steps to reproduce:**

Invoke `lobby:create` with an existing lobby name

**Expected results:**

Error message quotes lobby name in question without a prefix of any sort

**Actual results:**

Error message quotes lobby name in question prefixed with a dollar sign

**Relevant output:**

`HubException: Lobby with the name '$test3' already exists`

**Comment by ChrisRu** [comment]
Fixed in 41b4a93e3c550a5d5a466ccc87f4589792fe8ae7
